# Generated by Django 3.2.9 on 2021-11-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('note', models.TextField()),
                ('labels', models.CharField(choices=[('inspiration', 'Inspiration'), ('personal', 'Personal'), ('work', 'Work')], max_length=50)),
                ('images', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('author', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('note', models.TextField()),
                ('reminder_time', models.DateTimeField()),
                ('images', models.ImageField(upload_to='images/%Y/%m/%d')),
            ],
        ),
    ]
